import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, resolve } from 'path';
import { output, outputError } from '../../shared/output.js';

export interface StackInfo {
  stack: string[];
  manifests: string[];
}

export interface ProjectContext {
  projectPath: string;
  stack: string[];
  manifests: string[];
  testFramework: string | null;
  tddEnabled: boolean;
  conventions: string[];
  timestamp: string;
}

const MANIFEST_MAP: Array<{ file: string; stack: string }> = [
  { file: 'package.json', stack: 'node' },
  { file: 'go.mod', stack: 'go' },
  { file: 'Cargo.toml', stack: 'rust' },
  { file: 'pyproject.toml', stack: 'python' },
  { file: 'requirements.txt', stack: 'python' },
  { file: 'Gemfile', stack: 'ruby' },
  { file: 'composer.json', stack: 'php' },
  { file: 'pom.xml', stack: 'java' },
  { file: 'build.gradle', stack: 'java' },
  { file: 'build.gradle.kts', stack: 'kotlin' },
];

const CONVENTION_FILES = ['CLAUDE.md', 'AGENTS.md', '.cursorrules', 'GEMINI.md'];

export function detectStack(cwd: string): StackInfo {
  const stack = new Set<string>();
  const manifests: string[] = [];
  for (const { file, stack: s } of MANIFEST_MAP) {
    if (existsSync(join(cwd, file))) {
      stack.add(s);
      manifests.push(file);
    }
  }
  return { stack: [...stack], manifests };
}

export function detectTestFramework(cwd: string): string | null {
  const pkgPath = join(cwd, 'package.json');
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
      const deps = { ...(pkg.devDependencies ?? {}), ...(pkg.dependencies ?? {}) };
      if (deps.vitest) return 'vitest';
      if (deps.jest) return 'jest';
      if (deps.mocha) return 'mocha';
      if (deps['@playwright/test']) return 'playwright';
    } catch {
      // ignore malformed package.json
    }
  }

  const pyproject = join(cwd, 'pyproject.toml');
  if (existsSync(pyproject)) {
    const body = readFileSync(pyproject, 'utf-8');
    if (body.includes('pytest')) return 'pytest';
  }

  if (existsSync(join(cwd, 'go.mod'))) return 'go test';
  if (existsSync(join(cwd, 'Cargo.toml'))) return 'cargo test';

  return null;
}

export function detectConventions(cwd: string): string[] {
  return CONVENTION_FILES.filter((f) => existsSync(join(cwd, f)));
}

export function renderProjectContext(ctx: ProjectContext): string {
  const tdd = ctx.tddEnabled ? 'enabled' : 'disabled';
  return `# CTK Project Context

_Auto-generated by \`ctk init\` — safe to re-run._

- **Project path:** ${ctx.projectPath}
- **Generated:** ${ctx.timestamp}
- **Stack:** ${ctx.stack.length ? ctx.stack.join(', ') : '(unknown)'}
- **Manifests:** ${ctx.manifests.length ? ctx.manifests.join(', ') : '(none)'}
- **Test framework:** ${ctx.testFramework ?? '(none)'}
- **Strict TDD: ${tdd}**
- **Conventions files:** ${ctx.conventions.length ? ctx.conventions.join(', ') : '(none)'}
`;
}

export function runInit(cwdInput?: string): ProjectContext {
  const cwd = resolve(cwdInput ?? process.cwd());
  const { stack, manifests } = detectStack(cwd);
  const testFramework = detectTestFramework(cwd);
  const conventions = detectConventions(cwd);
  const ctx: ProjectContext = {
    projectPath: cwd,
    stack,
    manifests,
    testFramework,
    tddEnabled: testFramework !== null,
    conventions,
    timestamp: new Date().toISOString(),
  };

  const ctkDir = join(cwd, '.ctk');
  if (!existsSync(ctkDir)) mkdirSync(ctkDir, { recursive: true });

  writeFileSync(join(ctkDir, 'project-context.md'), renderProjectContext(ctx));
  writeFileSync(join(ctkDir, 'init.marker'), ctx.timestamp + '\n');

  return ctx;
}

export function initCommand(): void {
  try {
    const ctx = runInit();
    output(renderProjectContext(ctx));
  } catch (err) {
    outputError(`ctk init failed: ${(err as Error).message}`);
    process.exit(1);
  }
}
