import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync, statSync } from 'fs';
import { join, resolve } from 'path';
import { homedir } from 'os';
import { output, outputError } from '../../shared/output.js';

export interface SkillEntry {
  name: string;
  description: string;
  path: string;
  source: string;
}

export interface SkillSource {
  path: string;
  label: string;
}

export interface RegistryResult {
  entries: SkillEntry[];
  outputPath: string;
}

interface Frontmatter {
  name: string;
  description: string;
}

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---/;

export function parseSkillFrontmatter(body: string): Frontmatter | null {
  const match = FRONTMATTER_RE.exec(body);
  if (!match) return null;
  const raw = match[1] ?? '';
  const fields: Record<string, string> = {};
  let currentKey: string | null = null;
  for (const line of raw.split(/\r?\n/)) {
    const kv = /^([A-Za-z_][\w-]*):\s*(.*)$/.exec(line);
    if (kv) {
      currentKey = kv[1]!;
      fields[currentKey] = kv[2] ?? '';
    } else if (currentKey && line.trim().length > 0) {
      fields[currentKey] = `${fields[currentKey] ?? ''} ${line.trim()}`.trim();
    }
  }
  const name = fields['name']?.trim();
  const description = fields['description']?.trim();
  if (!name || !description) return null;
  return { name, description };
}

export function scanSkillsDir(dir: string): SkillEntry[] {
  if (!existsSync(dir)) return [];
  const entries: SkillEntry[] = [];
  let dirents: string[];
  try {
    dirents = readdirSync(dir);
  } catch {
    return [];
  }
  for (const child of dirents) {
    const childPath = join(dir, child);
    try {
      if (!statSync(childPath).isDirectory()) continue;
    } catch {
      continue;
    }
    const skillFile = join(childPath, 'SKILL.md');
    if (!existsSync(skillFile)) continue;
    const body = readFileSync(skillFile, 'utf-8');
    const fm = parseSkillFrontmatter(body);
    if (!fm) continue;
    entries.push({
      name: fm.name,
      description: fm.description,
      path: skillFile,
      source: '',
    });
  }
  return entries;
}

export function renderRegistry(entries: SkillEntry[]): string {
  if (entries.length === 0) {
    return `# CTK Skill Registry\n\nNo skills found.\n`;
  }
  const rows = entries
    .map((e) => `| ${e.name} | ${e.source} | ${e.description.replace(/\|/g, '\\|')} | ${e.path} |`)
    .join('\n');
  return `# CTK Skill Registry

_Auto-generated by \`ctk skill-registry\`._

| Name | Source | Description | Path |
|------|--------|-------------|------|
${rows}
`;
}

export function defaultSkillSources(cwd: string): SkillSource[] {
  return [
    { path: join(cwd, 'claude-dist/skills'), label: 'ctk' },
    { path: join(cwd, '.claude/skills'), label: 'project' },
    { path: join(homedir(), '.claude/skills'), label: 'global' },
  ];
}

export function runSkillRegistry(opts: { cwd?: string; sources?: SkillSource[] } = {}): RegistryResult {
  const cwd = resolve(opts.cwd ?? process.cwd());
  const sources = opts.sources ?? defaultSkillSources(cwd);

  const seen = new Set<string>();
  const entries: SkillEntry[] = [];
  for (const src of sources) {
    for (const entry of scanSkillsDir(src.path)) {
      if (seen.has(entry.name)) continue;
      seen.add(entry.name);
      entries.push({ ...entry, source: src.label });
    }
  }

  const ctkDir = join(cwd, '.ctk');
  if (!existsSync(ctkDir)) mkdirSync(ctkDir, { recursive: true });
  const outputPath = join(ctkDir, 'skill-registry.md');
  writeFileSync(outputPath, renderRegistry(entries));

  return { entries, outputPath };
}

export function skillRegistryCommand(): void {
  try {
    const r = runSkillRegistry();
    output(`${r.entries.length} skill(s) → ${r.outputPath}`);
  } catch (err) {
    outputError(`ctk skill-registry failed: ${(err as Error).message}`);
    process.exit(1);
  }
}
